name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    lint:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        steps:
            - uses: actions/checkout@v4
            - name: Install
              run: npm install
            - name: Check formatting
              run: npm run lint -- -c

    test:
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
        steps:
            - uses: actions/checkout@v4
            - name: Install
              run: npm install
            - name: Build and poseidon zkey
              run: sh scripts/build_poseidon.sh
            - name: Test
              run: npm test